import {defaultProductTaxonomy,validateProductTaxonomy,activateProductTaxonomy} from './product-taxonomy-model'
import type {ProductTaxonomy,ProductTaxonomyView} from './product-taxonomy-model'
type Stored={config:ProductTaxonomy;revision:string;previous:ProductTaxonomy|null}
const empty=():Stored=>({config:defaultProductTaxonomy(),revision:'seed',previous:null})
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('impetus-product-taxonomy-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('catalog');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('产品类型配置存储打开失败'))})}
async function read():Promise<Stored>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('catalog','readonly'),request=tx.objectStore('catalog').get('state');let state:Stored;request.onsuccess=()=>{state=request.result||empty()};tx.oncomplete=()=>{db.close();resolve(state)};tx.onerror=()=>{db.close();reject(new Error('产品类型配置读取失败'))}})}
async function write(revision:string,state:Stored){const db=await database();return new Promise<void>((resolve,reject)=>{let conflict=false;const tx=db.transaction('catalog','readwrite'),store=tx.objectStore('catalog'),request=store.get('state');request.onsuccess=()=>{if((request.result?.revision||'seed')!==revision){conflict=true;tx.abort();return}store.put(state,'state')};tx.oncomplete=()=>{db.close();resolve()};tx.onabort=()=>{db.close();reject(new Error(conflict?'配置已更新，请重新读取并预览':'产品类型配置保存失败'))};tx.onerror=()=>{db.close();reject(new Error('产品类型配置保存失败'))}})}
function view(state:Stored):ProductTaxonomyView{return {config:validateProductTaxonomy(state.config),revision:state.revision,storage:'browser',can_undo:state.previous!==null}}
export async function browserProductTaxonomy(){const value=view(await read());activateProductTaxonomy(value);return value}
export async function saveBrowserProductTaxonomy(config:ProductTaxonomy,revision:string){const previous=await read();if(previous.revision!==revision)throw new Error('配置已更新，请重新读取并预览');const next=validateProductTaxonomy(config);if(JSON.stringify(next)===JSON.stringify(validateProductTaxonomy(previous.config)))return view(previous);const state={config:next,revision:crypto.randomUUID(),previous:previous.config};await write(revision,state);const result=view(state);activateProductTaxonomy(result);return result}
export async function undoBrowserProductTaxonomy(revision:string){const previous=await read();if(previous.revision!==revision)throw new Error('配置已更新，请重新读取');if(!previous.previous)throw new Error('没有可撤销的配置');const state={config:previous.previous,revision:crypto.randomUUID(),previous:null};await write(revision,state);const result=view(state);activateProductTaxonomy(result);return result}
