import {useEffect,useState} from 'react'
import {Plus,Pencil,Download,Upload,Undo2,ArrowRight} from 'lucide-react'
import {api} from './api'
import {semanticPalette} from './semantics'
import {classifiedProductType,validateProductTaxonomy,normalizedTypeModel,typeTones,defaultProductTaxonomy} from './product-taxonomy-model'
import type {ProductTaxonomy,ProductTaxonomyView,ProductType,ProductTypeRule} from './product-taxonomy-model'
import type {SalesDataset} from './sales-lifecycle-model'
import './product-type-settings.css'
type Change={year:number;model:string;before:string;after:string}
const toneNames={violet:'紫色',cyan:'青色',amber:'橙色',blue:'蓝色',rose:'玫红',red:'红色',neutral:'灰色'}
function download(config:ProductTaxonomy){const url=URL.createObjectURL(new Blob([JSON.stringify({kind:'impetus-product-types',config},null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='英霏特产品类型配置.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function ProductTypeSettings({onChanged}:{onChanged:()=>Promise<void>}){
  const [view,setView]=useState<ProductTaxonomyView|null>(null),[draft,setDraft]=useState<ProductTaxonomy>(defaultProductTaxonomy),[history,setHistory]=useState<SalesDataset[]>([]),[tab,setTab]=useState('类型'),[type,setType]=useState<ProductType|null>(null),[rule,setRule]=useState<ProductTypeRule|null>(null)
  const [model,setModel]=useState(''),[override,setOverride]=useState(''),[query,setQuery]=useState(''),[preview,setPreview]=useState<{changes:Change[];count:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false)
  useEffect(()=>{let active=true;void api<ProductTaxonomyView>('/product-taxonomy').then(value=>{if(active){setView(value);setDraft(structuredClone(value.config))}}).catch(cause=>{if(active)setError(cause.message)});void api<SalesDataset[]>('/sales-history').then(value=>{if(active)setHistory(value)}).catch(cause=>{if(active)setError(cause.message)});return()=>{active=false}},[])
  const models=[...new Map(history.flatMap(data=>data.products.map(row=>[normalizedTypeModel(row.model),row.model] as const))).values()].sort()
  function changed(config:ProductTaxonomy){try{setDraft(validateProductTaxonomy(config));setPreview(null);setError('');setNotice('配置草稿已更新，预览后确认应用');setType(null);setRule(null)}catch(cause){setError((cause as Error).message)}}
  async function readLatest(){setBusy(true);try{const value=await api<ProductTaxonomyView>('/product-taxonomy');setView(value);setDraft(structuredClone(value.config));setPreview(null);setConflict(false);setType(null);setRule(null);setNotice('已载入最新配置')}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
  async function fail(cause:unknown){setError((cause as Error).message);setPreview(null);try{const latest=await api<ProductTaxonomyView>('/product-taxonomy');if(latest.revision!==view?.revision){setView(latest);setConflict(true)}}catch{/* Keep the draft for export. */}}
  async function previewDraft(){if(!view)return;setBusy(true);setError('');try{setPreview(await api('/product-taxonomy/preview','POST',{revision:view.revision,config:validateProductTaxonomy(draft)}))}catch(cause){await fail(cause)}finally{setBusy(false)}}
  async function apply(){if(!view||!preview||conflict)return;setBusy(true);setError('');try{const value=await api<ProductTaxonomyView>('/product-taxonomy','PUT',{revision:view.revision,config:draft});setView(value);setDraft(structuredClone(value.config));setPreview(null);setNotice('配置已应用，筛选、图表与后续型号同步使用');await onChanged();setHistory(await api('/sales-history'))}catch(cause){await fail(cause)}finally{setBusy(false)}}
  async function undo(){if(!view)return;setBusy(true);setError('');try{const value=await api<ProductTaxonomyView>('/product-taxonomy/undo','POST',{revision:view.revision});setView(value);setDraft(structuredClone(value.config));setPreview(null);setNotice('最近一次配置已撤销');await onChanged();setHistory(await api('/sales-history'))}catch(cause){await fail(cause)}finally{setBusy(false)}}
  async function importFile(file?:File){if(!file)return;setError('');try{if(file.size>2*1024*1024)throw new Error('配置文件应不超过 2 MB');const data=JSON.parse(await file.text());if(data.kind!=='impetus-product-types')throw new Error('请选择产品类型配置备份');changed(data.config)}catch(cause){setError((cause as Error).message)}}
  return <div className="product-type-settings"><header><div><h2>产品类型与归类</h2><p>保存位置：{view?.storage==='server'?'共享数据库':'本浏览器'} · 类型、颜色与规则由页面维护</p></div><a className="text-button" href="#products">查看产品与销售<ArrowRight size={14}/></a></header><div className="type-editor-tabs" role="group" aria-label="产品类型配置项目">{['类型','自动归类','型号归类','备份'].map(value=><button key={value} aria-pressed={tab===value} onClick={()=>{setTab(value);setType(null);setRule(null)}}>{value}</button>)}</div>
    {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="settings-notice" role="status">{notice}</p>}{conflict&&<div className="type-conflict"><p>配置版本已更新。当前草稿可导出；载入最新配置后重新编辑与预览。</p><button className="button" disabled={busy} onClick={()=>void readLatest()}>载入最新配置</button></div>}
    {tab==='类型'&&<><div className="type-editor-heading"><span>{draft.categories.length} 个产品类型</span><button className="button" disabled={busy} onClick={()=>setType({id:'type-'+crypto.randomUUID(),name:'',tone:'blue',active:true,order:Math.min(10000,draft.categories.length*10+10),aliases:[]})}><Plus size={14}/>新增产品类型</button></div><div className="type-catalog-list">{draft.categories.map(row=><div key={row.id}><span className="type-color-dot" style={{background:semanticPalette[row.tone].solid}}/><strong>{row.name}</strong><span>{row.active?'启用':'停用'} · 排序 {row.order}{row.id===draft.fallback_id?' · 兜底类型':''}</span><button className="text-button" disabled={busy} aria-label={`编辑产品类型 ${row.name}`} onClick={()=>setType(structuredClone(row))}><Pencil size={13}/>编辑</button></div>)}</div>
    {type&&<form className="type-edit-form" onSubmit={event=>{event.preventDefault();const old=draft.categories.find(row=>row.id===type.id),next={...type,aliases:[...new Set([...type.aliases,...(old&&old.name!==type.name?[old.name]:[])])]};changed({...draft,categories:[...draft.categories.filter(row=>row.id!==type.id),next]})}}><h3>{draft.categories.some(row=>row.id===type.id)?'编辑产品类型':'新增产品类型'}</h3><div className="type-form-grid"><label>类型名称<input aria-label="产品类型名称" required maxLength={50} value={type.name} disabled={busy} onChange={event=>setType({...type,name:event.target.value})}/></label><label>显示颜色<select aria-label="产品类型颜色" value={type.tone} disabled={busy} onChange={event=>setType({...type,tone:event.target.value as ProductType['tone']})}>{typeTones.map(tone=><option key={tone} value={tone}>{toneNames[tone]}</option>)}</select></label><label>排序值<input aria-label="产品类型排序" type="number" min="0" max="10000" value={type.order} disabled={busy} onChange={event=>setType({...type,order:Number(event.target.value)})}/></label><label className="type-check"><input type="checkbox" checked={type.active} disabled={busy||type.id===draft.fallback_id} onChange={event=>setType({...type,active:event.target.checked})}/>作为可选类型启用</label></div><div className="type-form-actions"><button className="button" type="button" onClick={()=>setType(null)}>取消</button><button className="button" disabled={busy}>加入配置草稿</button></div></form>}<p className="type-rule-note">改名保留稳定类型 ID；停用不删除历史归类或已有规则，要停止自动归类请停用对应规则。</p></>}
    {tab==='自动归类'&&<><div className="type-editor-heading"><span>{draft.rules.length} 条归类规则</span><button className="button" disabled={busy} onClick={()=>setRule({id:'rule-'+crypto.randomUUID(),kind:'prefix',value:'',category_id:draft.categories.find(row=>row.active&&row.id!==draft.fallback_id)?.id||draft.fallback_id,priority:100,active:true})}><Plus size={14}/>新增归类规则</button></div><div className="type-rule-scroll"><table><thead><tr><th>匹配方式</th><th>匹配内容</th><th>目标类型</th><th>优先级 / 状态</th><th>操作</th></tr></thead><tbody>{draft.rules.map(row=><tr key={row.id}><td>{row.kind==='exact'?'完整型号':'型号前缀'}</td><td>{row.value}</td><td>{draft.categories.find(type=>type.id===row.category_id)?.name}</td><td>{row.priority} · {row.active?'启用':'停用'}</td><td><button className="text-button" disabled={busy} aria-label={`编辑归类规则 ${row.value}`} onClick={()=>setRule(structuredClone(row))}>编辑</button></td></tr>)}</tbody></table></div>
    {rule&&<form className="type-edit-form" onSubmit={event=>{event.preventDefault();changed({...draft,rules:[...draft.rules.filter(row=>row.id!==rule.id),rule]})}}><h3>归类规则</h3><div className="type-form-grid"><label>匹配方式<select aria-label="归类匹配方式" value={rule.kind} disabled={busy} onChange={event=>setRule({...rule,kind:event.target.value as ProductTypeRule['kind']})}><option value="exact">完整型号</option><option value="prefix">型号前缀</option></select></label><label>匹配内容<input aria-label="归类匹配内容" required maxLength={200} placeholder="例如 Z- 或 122N" value={rule.value} disabled={busy} onChange={event=>setRule({...rule,value:event.target.value})}/></label><label>目标类型<select aria-label="规则目标类型" value={rule.category_id} disabled={busy} onChange={event=>setRule({...rule,category_id:event.target.value})}>{draft.categories.filter(row=>row.active||row.id===rule.category_id).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>同类优先级<input aria-label="归类规则优先级" type="number" min="0" max="10000" value={rule.priority} disabled={busy} onChange={event=>setRule({...rule,priority:Number(event.target.value)})}/></label><label className="type-check"><input type="checkbox" checked={rule.active} disabled={busy} onChange={event=>setRule({...rule,active:event.target.checked})}/>启用规则</label></div><div className="type-form-actions"><button type="button" className="button" onClick={()=>setRule(null)}>取消</button><button className="button" disabled={busy}>加入配置草稿</button></div></form>}<p className="type-rule-note">单型号指定优先，其次完整型号，再按前缀；同类数字越小优先级越高。匹配忽略空格和大小写，不合并型号。</p></>}
    {tab==='型号归类'&&<><form className="type-edit-form" onSubmit={event=>{event.preventDefault();const key=normalizedTypeModel(model),next=draft.overrides.filter(row=>normalizedTypeModel(row.model)!==key);if(override)next.push({model,category_id:override});changed({...draft,overrides:next})}}><h3>单个型号指定类型</h3><div className="type-form-grid"><label>完整型号<input aria-label="单独归类型号" required list="taxonomy-model-list" maxLength={200} value={model} disabled={busy} onChange={event=>{setModel(event.target.value);setOverride(draft.overrides.find(row=>normalizedTypeModel(row.model)===normalizedTypeModel(event.target.value))?.category_id||'')}}/><datalist id="taxonomy-model-list">{models.map(model=><option key={model}>{model}</option>)}</datalist></label><label>归类结果<select aria-label="型号指定类型" value={override} disabled={busy} onChange={event=>setOverride(event.target.value)}><option value="">遵循自动归类规则</option>{draft.categories.filter(row=>row.active||row.id===override).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div><div className="type-form-actions"><button className="button" disabled={busy}>加入配置草稿</button></div></form><label className="type-model-search">查找已有型号<input aria-label="搜索归类型号" value={query} onChange={event=>setQuery(event.target.value)} placeholder="例如 122N"/></label><div className="type-rule-scroll"><table><thead><tr><th>型号</th><th>草稿归类</th><th>方式</th></tr></thead><tbody>{models.filter(model=>model.toLowerCase().includes(query.toLowerCase())).slice(0,100).map(model=><tr key={model}><td>{model}</td><td>{classifiedProductType(model,draft).name}</td><td>{draft.overrides.some(row=>normalizedTypeModel(row.model)===normalizedTypeModel(model))?'单独指定':'自动规则'}</td></tr>)}</tbody></table></div></>}
    {tab==='备份'&&<><div className="type-backup-actions"><button className="button" onClick={()=>download(draft)}><Download size={14}/>导出当前配置草稿</button><label className="button"><Upload size={14}/>导入类型配置<input aria-label="导入产品类型配置" type="file" accept=".json" disabled={busy} onChange={event=>{void importFile(event.target.files?.[0]);event.target.value=''}}/></label><button className="button" disabled={busy||!view?.can_undo} onClick={()=>void undo()}><Undo2 size={14}/>撤销最近配置</button></div><p className="type-rule-note">导入只更新草稿，预览后确认应用；配置备份不含销量、文件或密码。浏览器预览配置各自保留，正式服务使用共享数据库。</p></>}
    {preview&&<section className="type-preview" aria-label="产品归类变更预览"><h3>预计影响 {preview.count} 条年度型号归类</h3>{preview.changes.length?<div className="type-rule-scroll"><table><thead><tr><th>年度</th><th>型号</th><th>当前类型</th><th>新类型</th></tr></thead><tbody>{preview.changes.slice(0,50).map((row,i)=><tr key={i}><td>{row.year}</td><td>{row.model}</td><td>{row.before}</td><td>{row.after}</td></tr>)}</tbody></table></div>:<p>已有型号归类没有变化；类型、颜色、排序与新规则仍可应用。</p>}<p>仅调整归类与展示，不修改型号、数量、日期、售价或项目。</p></section>}
    <footer className="type-apply-actions"><span>编辑表单 → 加入草稿 → 预览配置 → 确认应用</span><button className="button" disabled={busy||!view||conflict} onClick={()=>void previewDraft()}>预览配置变更</button>{preview&&<button className="button primary" disabled={busy||conflict} onClick={()=>void apply()}>确认应用配置</button>}</footer>
  </div>
}
