import {validateProjectTable,expandedProjectTable} from './project-table-model'
import type {ProjectTableData,ProjectTableView} from './project-table-model'
type Stored={data:ProjectTableData;previous:ProjectTableData|null}
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('impetus-project-table-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('tables');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('项目表存储打开失败'))})}
async function seed(base:string){const response=await fetch(base+'project-table/current.json',{cache:'no-store'});if(!response.ok)throw new Error('项目表读取失败');return validateProjectTable(await response.json())}
const view=(value:Stored):ProjectTableView=>({...expandedProjectTable(value.data),storage:'browser',can_undo:value.previous!==null})
export async function browserProjectTable(base:string){const initial=await seed(base),key='table:'+initial.revision,db=await database();return new Promise<{key:string;stored:Stored;view:ProjectTableView}>((resolve,reject)=>{const tx=db.transaction('tables','readonly'),request=tx.objectStore('tables').get(key);let stored:Stored;request.onsuccess=()=>{stored=request.result||{data:initial,previous:null}};tx.oncomplete=()=>{db.close();try{resolve({key,stored,view:view(stored)})}catch(error){reject(error)}};tx.onerror=()=>{db.close();reject(new Error('项目表读取失败'))}})}
export async function saveBrowserProjectTable(base:string,data:ProjectTableData,revision:string,undo=false){const current=await browserProjectTable(base);if(current.view.revision!==revision)throw new Error('项目表已更新，请重新读取');const next=undo?current.stored.previous:validateProjectTable(data);if(!next)throw new Error('没有可撤销的项目表');if(!undo&&JSON.stringify({...next,revision:''})===JSON.stringify({...expandedProjectTable(current.stored.data),revision:''}))return current.view
  const stored:Stored={data:{...next,revision:crypto.randomUUID()},previous:undo?null:current.stored.data},db=await database()
  await new Promise<void>((resolve,reject)=>{let conflict=false;const tx=db.transaction('tables','readwrite'),store=tx.objectStore('tables'),request=store.get(current.key);request.onsuccess=()=>{if((request.result?.data.revision||current.view.revision)!==revision){conflict=true;tx.abort()}else store.put(stored,current.key)};tx.oncomplete=()=>{db.close();resolve()};tx.onabort=()=>{db.close();reject(new Error(conflict?'项目表已更新，请重新读取':'项目表保存失败'))};tx.onerror=()=>{db.close();reject(new Error('项目表保存失败'))}})
  return view(stored)
}
