import {useEffect,useState,useRef} from 'react'
import {Plus,Pencil,Search,Download,Undo2,RefreshCw} from 'lucide-react'
import {api} from './api'
import {projectColumnNames,projectTableProgress,filterProjectTable,replaceProjectRow,validateProjectTable,projectTableStageTone} from './project-table-model'
import type {ProjectTableData,ProjectTableRow,ProjectTableView,ProjectTableField} from './project-table-model'
import {toneStyle} from './semantics'
import './project-table.css'
function download(data:ProjectTableData){const url=URL.createObjectURL(new Blob([JSON.stringify({kind:'impetus-project-table',data},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='英霏特项目表.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function ProjectTable(){
  const [data,setData]=useState<ProjectTableView|null>(null),[scope,setScope]=useState('all'),[query,setQuery]=useState(''),[draft,setDraft]=useState<ProjectTableRow|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[imported,setImported]=useState<ProjectTableData|null>(null)
  const dialog=useRef<HTMLDialogElement>(null)
  async function load(){setError('');try{setData(await api<ProjectTableView>('/project-table'))}catch(cause){setError((cause as Error).message)}}
  useEffect(()=>{void load()},[])
  useEffect(()=>{if(draft)dialog.current?.showModal()},[draft])
  async function save(next:ProjectTableData){if(!data)return;setBusy(true);setError('');try{setData(await api('/project-table','PUT',{revision:data.revision,data:next}));setDraft(null);setImported(null);setNotice('项目表已保存')}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
  async function undo(){if(!data)return;setBusy(true);setError('');try{setData(await api('/project-table/undo','POST',{revision:data.revision}));setNotice('最近一次项目表修改已撤销')}catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
  async function importFile(file?:File){if(!file||!data)return;try{if(file.size>5*1024*1024)throw new Error('项目备份应不超过 5 MB');const value=JSON.parse(await file.text());if(value.kind!=='impetus-project-table')throw new Error('请选择项目表 JSON 备份');const next=validateProjectTable({...value.data,fields:data.fields});setImported(next);setError('')}catch(cause){setError((cause as Error).message)}}
  const rows=data?filterProjectTable(data.rows,scope,query):[]
  function cell(row:ProjectTableRow,field:ProjectTableField){const value=row[field];if(field==='stage')return <span className="project-table-stage" style={toneStyle(projectTableStageTone(row.stage))}>{row.stage||'未设阶段'}</span>;if(field==='progress'||field==='planned_progress')return <span className="project-table-progress">{value!=null&&<i><b style={{width:value+'%'}}/></i>}{projectTableProgress(value as number|null)}</span>;return value?<span className="project-table-text">{value}</span>:<span className="project-table-missing">未填写</span>}
  return <section className="compact-project-table" aria-label="在研与预研项目表">
    <div className="project-table-toolbar"><div className="project-table-scopes" role="group" aria-label="项目表范围">{[['all','全部'],['active','在研'],['research','预研'],['unset','未设阶段']].map(([value,label])=><button key={value} aria-pressed={scope===value} onClick={()=>setScope(value)}>{label}<span>{data?filterProjectTable(data.rows,value,'').length:0}</span></button>)}</div><label className="project-table-search"><Search size={15}/><input aria-label="搜索项目表" placeholder="搜索项目名称" value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="button" disabled={!data||busy} onClick={()=>{if(data){const row:Record<string,unknown>={id:'pt-'+crypto.randomUUID()};for(const field of data.fields)row[field]=field==='progress'||field==='planned_progress'?null:'';setDraft(row as ProjectTableRow)}}}><Plus size={14}/>新增项目</button></div>
    {error&&<div className="form-error" role="alert">{error}<button className="text-button" disabled={busy} onClick={()=>void load()}>重新读取</button></div>}{notice&&<p className="settings-notice" role="status">{notice}</p>}
    {!data&&!error&&<p className="project-table-missing"><RefreshCw size={14}/> 正在读取项目表…</p>}
    {data&&<><div className="project-table-scroll" style={{'--project-table-min':(data.fields.length>4?1750:720)+'px'} as React.CSSProperties}><table><thead><tr>{data.fields.map(field=><th scope="col" key={field} className={'column-'+field}>{projectColumnNames[field]}</th>)}<th scope="col" className="column-actions">操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{data.fields.map(field=><td key={field} className={'column-'+field} title={typeof row[field]==='string'?row[field] as string:undefined}>{cell(row,field)}</td>)}<td className="column-actions"><button className="text-button" aria-label={'编辑项目表 '+row.name} disabled={busy} onClick={()=>setDraft({...row})}><Pencil size={13}/>编辑</button></td></tr>)}</tbody></table>{!rows.length&&<p className="project-table-empty">暂无匹配项目。</p>}</div><footer className="project-table-footer"><span>{rows.length} 个项目 · {data.storage==='server'?'共享数据库':'本浏览器'}</span><button className="text-button" disabled={busy} onClick={()=>download(data)}><Download size={13}/>备份项目表</button><label className="text-button">导入备份<input aria-label="导入项目表备份" disabled={busy} type="file" accept=".json" onChange={event=>{void importFile(event.target.files?.[0]);event.target.value=''}}/></label><button className="text-button" disabled={busy||!data.can_undo} onClick={()=>void undo()}><Undo2 size={13}/>撤销最近修改</button></footer></>}
    {imported&&<section className="project-table-import" aria-label="项目表导入预览"><h3>备份包含 {imported.rows.length} 个项目</h3><p>确认后替换当前项目表，原有销量不变；仅采用当前可维护字段。</p><p>{imported.rows.slice(0,3).map(row=>row.name).join(' · ')}</p><button className="button" disabled={busy} onClick={()=>setImported(null)}>取消导入</button><button className="button primary" disabled={busy} onClick={()=>void save(imported)}>确认导入项目表</button></section>}
    {draft&&data&&<dialog ref={dialog} className="editor" aria-labelledby="project-table-editor-title" onCancel={event=>{if(busy)event.preventDefault();else setDraft(null)}}><form onSubmit={event=>{event.preventDefault();try{void save(replaceProjectRow(data,draft))}catch(cause){setError((cause as Error).message)}}}><div className="dialog-head"><h2 id="project-table-editor-title">{data.rows.some(row=>row.id===draft.id)?'编辑项目':'新增项目'}</h2></div><div className="form-body">{data.fields.map(field=><label key={field} className={'project-table-edit-field '+(field==='description'?'full':'')}>{projectColumnNames[field]}{field==='description'?<textarea aria-label={projectColumnNames[field]} rows={3} value={String(draft[field]??'')} disabled={busy} onChange={event=>setDraft({...draft,[field]:event.target.value})}/>:<input aria-label={projectColumnNames[field]} list={field==='stage'?'project-table-stage-options':undefined} required={field==='name'} type={field==='progress'||field==='planned_progress'?'number':'text'} min={0} max={100} step="0.01" value={draft[field]??''} disabled={busy} onChange={event=>setDraft({...draft,[field]:field==='progress'||field==='planned_progress'?(event.target.value===''?null:Number(event.target.value)):event.target.value})}/>}</label>)}<datalist id="project-table-stage-options">{[...new Set(['预研','EVT','DVT','PVT','MP',...data.rows.map(row=>row.stage).filter(Boolean)])].map(stage=><option key={stage}>{stage}</option>)}</datalist></div>{error&&<p className="form-error">{error}</p>}<div className="dialog-footer"><button type="button" className="button" disabled={busy} onClick={()=>setDraft(null)}>取消</button><button className="button primary" disabled={busy}>保存项目</button></div></form></dialog>}
  </section>
}
