import {useEffect,useRef,useState} from 'react'
import {Upload,Download,Undo2,X,Database,Check} from 'lucide-react'
import {api} from './api'
import {salesBackupRows,parseSalesBackup} from './sales-maintenance-model'
import type {SalesBatch,SalesCell,SalesDataView,SalesPlan} from './sales-maintenance-model'
import './sales-maintenance.css'
const number=(value:number|null)=>value===null?'未录入':new Intl.NumberFormat('zh-CN').format(value)
function download(name:string,type:string,text:string){const url=URL.createObjectURL(new Blob([text],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function SalesDataManager({initialYear,onClose,onSaved}:{initialYear:number;onClose:()=>void;onSaved:(view:SalesDataView,year?:number)=>void}){
  const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState<SalesDataView|null>(null),[tab,setTab]=useState<'manual'|'excel'|'history'>('manual'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const [year,setYear]=useState(initialYear||new Date().getFullYear()),[month,setMonth]=useState(1),[model,setModel]=useState(''),[units,setUnits]=useState(''),[missing,setMissing]=useState(false),[through,setThrough]=useState(12),[mode,setMode]=useState<SalesBatch['mode']>('fill'),[rows,setRows]=useState<SalesCell[]>([]),[fileLabel,setFileLabel]=useState(''),[plan,setPlan]=useState<SalesPlan|null>(null),[batch,setBatch]=useState<SalesBatch|null>(null),[backupSource,setBackupSource]=useState(false)
  useEffect(()=>{const focus=document.activeElement as HTMLElement|null;dialog.current?.showModal();void api<SalesDataView>('/sales-data').then(setData).catch(cause=>setError(cause.message));return()=>{dialog.current?.close();focus?.focus({preventScroll:true})}},[])
  function invalidate(){setPlan(null);setBatch(null);setNotice('');setError('')}
  function switchTab(value:typeof tab){setTab(value);invalidate()}
  async function preview(){if(!data)return;setBusy(true);setError('');setNotice('');try{
    let input=rows
    if(tab==='manual'){if(!model.trim())throw new Error('请填写产品型号');if(!missing&&(!units.trim()||!/^\d+$/.test(units.trim())))throw new Error('请填写非负整数销量，或勾选未录入');input=[{year,month,model,units:missing?null:Number(units)}]}
    const request:SalesBatch={revision:data.revision,mode:tab==='manual'?'replace':mode,source:tab==='manual'?'manual':backupSource?'backup':'excel',rows:input}
    const result=await api<SalesPlan>('/sales-data/preview','POST',request);setPlan(result);setBatch(request)
  }catch(cause){setError((cause as Error).message);setPlan(null);setBatch(null);try{setData(await api<SalesDataView>('/sales-data'))}catch{/* Retain draft inputs. */}}finally{setBusy(false)}}
  async function save(){if(!batch||!data)return;setBusy(true);setError('');try{const result=await api<SalesDataView>('/sales-data/commit','POST',batch);setData(result);setPlan(null);setBatch(null);setNotice(`已保存 ${result.result?.changed||0} 个型号月份合计`);onSaved(result,Math.max(...batch.rows.map(row=>row.year)))}catch(cause){setError((cause as Error).message);setPlan(null);setBatch(null);try{setData(await api<SalesDataView>('/sales-data'))}catch{/* Keep the previous values visible. */}}finally{setBusy(false)}}
  async function fileChanged(file?:File){invalidate();setRows([]);setFileLabel('');if(!file)return;setBusy(true);try{const {readSalesFile}=await import('./sales-excel');const result=await readSalesFile(file,year,through);setRows(result.rows);setYear(result.year);setFileLabel(`${file.name} · 解析年度 ${result.year} · ${result.format} · ${result.rows.length} 条合计`);setBackupSource(false)}catch(cause){setError((cause as Error).message);setPlan(null);setBatch(null);try{setData(await api<SalesDataView>('/sales-data'))}catch{/* Retain draft inputs. */}}finally{setBusy(false)}}
  async function backupChanged(file?:File){invalidate();if(!file)return;setBusy(true);try{if(file.size>5*1024*1024)throw new Error('备份应不超过 5 MB');setRows(parseSalesBackup(await file.text()));setFileLabel(file.name+' · 销售备份');setBackupSource(true);setTab('excel')}catch(cause){setError((cause as Error).message);setPlan(null);setBatch(null);try{setData(await api<SalesDataView>('/sales-data'))}catch{/* Retain draft inputs. */}}finally{setBusy(false)}}
  async function undo(){if(!data)return;const last=data.latest_undoable;if(!last)return;setBusy(true);setError('');try{const result=await api<SalesDataView>(`/sales-data/changes/${last.id}/undo`,'POST',{revision:data.revision});setData(result);if(!result.history.some(data=>data.year===year))setYear(result.history[0]?.year||initialYear);invalidate();setNotice('最近一次维护已撤销');onSaved(result)}catch(cause){setError((cause as Error).message);setPlan(null);setBatch(null);try{setData(await api<SalesDataView>('/sales-data'))}catch{/* Retain draft inputs. */}}finally{setBusy(false)}}
  return <dialog ref={dialog} className="sales-data-dialog" aria-labelledby="sales-data-title" onCancel={event=>{event.preventDefault();if(!busy)onClose()}}><header><div><h2 id="sales-data-title"><Database size={19}/>销售数据维护</h2><span>保存位置：{data?.storage==='server'?'共享数据库':'本浏览器'}</span></div><button className="icon-button" aria-label="关闭数据维护" disabled={busy} onClick={onClose}><X size={19}/></button></header>
    <div className="sales-data-tabs" role="group" aria-label="数据维护方式">{(['manual','excel','history'] as const).map(value=><button key={value} aria-pressed={tab===value} disabled={busy} onClick={()=>switchTab(value)}>{{manual:'手动填写',excel:'Excel 导入',history:'维护记录与备份'}[value]}</button>)}</div>
    <div className="sales-data-body">{!data&&!error&&<p>正在读取销售数据…</p>}{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="sales-data-notice" role="status"><Check size={15}/>{notice}</p>}
      {tab==='manual'&&<div className="sales-data-form"><label>年份<input aria-label="维护年份" type="number" min="1900" max="9998" value={year} disabled={busy} onChange={event=>{setYear(Number(event.target.value));invalidate()}}/></label><label>月份<select aria-label="维护月份" value={month} disabled={busy} onChange={event=>{setMonth(Number(event.target.value));invalidate()}}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{i+1} 月</option>)}</select></label><label className="full">产品型号<input aria-label="维护产品型号" list="sales-maintenance-models" placeholder="选择已有型号或填写新型号" value={model} disabled={busy} onChange={event=>{setModel(event.target.value);invalidate()}}/><datalist id="sales-maintenance-models">{[...new Set(data?.history.flatMap(data=>data.products.map(row=>row.model))||[])].sort().map(model=><option key={model}>{model}</option>)}</datalist></label><label>该型号当月合计销量<input aria-label="维护合计销量" inputMode="numeric" value={units} disabled={busy||missing} placeholder="例如 2000" onChange={event=>{setUnits(event.target.value);invalidate()}}/></label><label className="sales-data-checkbox"><input type="checkbox" checked={missing} disabled={busy} onChange={event=>{setMissing(event.target.checked);invalidate()}}/>设为未录入</label><p className="full sales-data-rule">填写的是型号月合计，不与原数量相加；0 表示明确零销量。型号按统一规则归类，支持电池、配件、干烧、雾化器和一次性。</p></div>}
      {tab==='excel'&&<><div className="sales-import-controls"><label>未注明年份时使用<input aria-label="Excel 默认年份" type="number" value={year} disabled={busy} onChange={event=>{setYear(Number(event.target.value));invalidate();setRows([]);setFileLabel('')}}/></label><label>宽表导入至<select aria-label="Excel 截止月份" value={through} disabled={busy} onChange={event=>{setThrough(Number(event.target.value));invalidate();setRows([]);setFileLabel('')}}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{i+1} 月</option>)}</select></label><label>已有值处理<select aria-label="导入更新方式" value={mode} disabled={busy} onChange={event=>{setMode(event.target.value as SalesBatch['mode']);invalidate()}}><option value="fill">只补空缺（默认）</option><option value="replace">覆盖已有合计</option></select></label></div><label className="sales-upload"><Upload size={19}/><strong>选择 Excel / CSV</strong><input aria-label="上传销售 Excel" type="file" accept=".xlsx,.csv" disabled={busy} onChange={event=>{void fileChanged(event.target.files?.[0]);event.target.value=''}}/></label>{fileLabel&&<p className="sales-data-file">{fileLabel}</p>}<p className="sales-data-rule">支持现有 XLSX Jan–Dec 宽表与 UTF-8 CSV / XLSX 的“年份、月份、产品型号、销量”长表。空白不覆盖；重复上传不累加；客户列、备注和隐藏页不保存。</p><button className="text-button" onClick={()=>download('销售数据模板.csv','text/csv;charset=utf-8','\uFEFF年份,月份,产品型号,销量\r\n')}><Download size={14}/>下载 CSV 模板（可用 Excel 填写并另存 .xlsx）</button></>}
      {plan&&<section className="sales-import-preview" aria-label="维护变更预览"><h3>变更预览</h3><p>待更新 <strong>{plan.changed}</strong> 条 · 已有值跳过 {plan.skipped} 条 · 完全相同 {plan.identical} 条</p>{plan.changes.length>0?<div className="sales-preview-scroll"><table><thead><tr><th>年月</th><th>型号</th><th>原合计</th><th>新合计</th></tr></thead><tbody>{plan.changes.slice(0,50).map(row=><tr key={`${row.year}/${row.model}/${row.month}`}><td>{row.year}-{String(row.month).padStart(2,'0')}</td><td>{row.model}</td><td>{number(row.before)}</td><td>{number(row.units)}</td></tr>)}</tbody></table>{plan.changes.length>50&&<p>预览前 50 条；确认后保存全部 {plan.changed} 条。</p>}</div>:<p>没有需要更新的合计，原数据保持不变。</p>}</section>}
      {tab==='history'&&<><div className="sales-backup-actions"><label>备份年度 <select aria-label="备份年度" value={year} onChange={event=>setYear(Number(event.target.value))}>{data?.history.map(data=><option key={data.year} value={data.year}>{data.year} 年</option>)}</select></label><button className="button" disabled={!data||busy} onClick={()=>{if(data)download('英霏特年度销量备份.json','application/json',JSON.stringify({schema_version:1,kind:'impetus-sales-backup',rows:salesBackupRows(data.history.filter(data=>data.year===year))},null,2))}}><Download size={14}/>导出年度销量备份</button><label className="button"><Upload size={14}/>导入备份<input aria-label="上传销售备份" type="file" accept=".json" disabled={busy} onChange={event=>{void backupChanged(event.target.files?.[0]);event.target.value=''}}/></label><button className="button" disabled={busy||!data?.latest_undoable} onClick={()=>void undo()}><Undo2 size={14}/>撤销最近一次维护</button></div><div className="sales-changes">{data?.changes.map(row=><div key={row.id}><strong>{row.label}</strong><span>{row.count} 条合计 · {new Date(row.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</span><small>{row.undone?'已撤销':'已保存'}</small></div>)}</div>{!data?.changes.length&&<p className="sales-data-rule">暂无维护记录，当前为已导入的基础数据。</p>}<p className="sales-data-rule">年度销量备份包含空缺，不含售价或项目文件；恢复空缺请选择覆盖并预览确认。GitHub 预览的维护值保存在本浏览器；正式服务通过数据库共享。</p></>}
    </div><footer><span>原始导入文件保持不变</span>{tab!=='history'&&<button className="button" disabled={busy||!data||tab==='excel'&&!rows.length} onClick={()=>void preview()}>预览变更</button>}{plan&&plan.changed>0&&<button className="button primary" disabled={busy} onClick={()=>void save()}>确认保存 {plan.changed} 条</button>}<button className="button" disabled={busy} onClick={onClose}>完成</button></footer>
  </dialog>
}
