export type Product = { id: string; name: string; sku: string; category: string; status: string; owner: string; description: string }
export type Sale = { id: string; product_id: string; month: string; revenue_cents: number; units: number; channel: string; note: string }
export type ProjectImportInfo = { file: string; priority: string; phase: string; status: string; category: string; progress_known: boolean; source_count: number }
export type ProjectProfile = { priority: string; phase: string; structural_owner: string; target: string; key_plan: string; risk_note: string; actual_completed_on: string; progress_known: boolean }
export type Project = { id: string; name: string; product_id: string; stage: string; status: string; owner: string; due_date: string; progress: number; description: string; profile?: ProjectProfile; import_info?: ProjectImportInfo }
export type ProjectSourceRecord = { sheet: string; hidden: boolean; row_start: number; row_end: number; updated: string; fields: Record<string, string>; display_fields?: Record<string, string>; history?: { row: number; label: string; text: string }[]; images: string[]; issues: { row: number; text: string; completion: string }[]; timeline: { cell: string; activity: string; label: string; row_kind: string; raw: string; date: string }[]; raw_rows: { row: number; cells: { cell: string; value: string; formula: string }[] }[]; comments: Record<string, string> }
export type ProjectSource = { file: string; sha256: string; code: string; progress_known: boolean; warnings: string[]; records: ProjectSourceRecord[] }
export type Task = { id: string; project_id: string; title: string; owner: string; due_date: string; status: string; description?: string }
export type ProjectMilestone = { id: string; project_id: string; name: string; owner: string; planned_start: string; planned_end: string; actual_start: string; actual_end: string; status: string; recorded_text: string; note: string; sort_order: number }
export type ProjectUpdate = { id: string; project_id: string; content: string; occurred_on: string; author: string; kind: string; created_at: string }
export type ProjectImage = { id: string; project_id: string; filename: string; caption: string; sort_order: number; url?: string }
export type ProjectDetails = { profile: ProjectProfile; milestones: ProjectMilestone[]; updates: ProjectUpdate[]; images: ProjectImage[] }
export type Signal = { id: string; kind: string; brand: string; title: string; content: string; sentiment: string; source_url: string; occurred_on: string }
export type Seat = { id: string; name: string; kind: string; provider: string; status: string; note: string }
export type Job = { id: string; name: string; frequency: string; enabled: boolean; next_run_at: string; last_run_at: string | null }
export type Report = { id: string; title: string; month: string; content: string; generated_at: string; job_id: string | null; source: string }
export type KnowledgeDocument = { id: string; project_id: string; template_id: string; stage: string; title: string; owner: string; status: '草稿' | '待评审' | '已归档'; content: string; updated_at: string }
export type Category = { id: string; scope: 'project' | 'report'; name: string; active: boolean; sort_order: number }
export type CustomField = { id: string; scope: 'project' | 'report'; key: string; label: string; kind: 'text' | 'number' | 'date' | 'select'; options: string[]; required: boolean; active: boolean; sort_order: number }
export type EntityMeta = { scope: 'project' | 'report'; entity_id: string; category_id: string; values: Record<string, string>; updated_at: string }
export type Activity = { id: string; action: string; created_at: string }
export type Workspace = { products: Product[]; sales: Sale[]; projects: Project[]; tasks: Task[]; signals: Signal[]; seats: Seat[]; jobs: Job[]; reports: Report[]; knowledge_documents: KnowledgeDocument[]; categories: Category[]; custom_fields: CustomField[]; entity_meta: EntityMeta[]; activity: Activity[]; project_details?: Record<string, ProjectDetails> }
export type Dashboard = { month: string; revenue_cents: number; previous_revenue_cents: number; growth_pct: number | null; top_product_share: number; risk_threshold: number; product_count: number; active_projects: number; overdue_tasks: number; product_sales: { product_id: string; name: string; category: string; revenue_cents: number; share: number }[]; trend: { month: string; revenue_cents: number }[]; category_sales: { category: string; revenue_cents: number; share: number }[] }
export type Entity = 'products' | 'sales' | 'projects' | 'tasks' | 'signals' | 'seats' | 'jobs'
export type Field = { key: string; label: string; type?: string; required?: boolean; options?: { label: string; value: string }[]; hint?: string; min?: number; max?: number; step?: string }
export type EditState = { entity: Entity; id?: string; title: string; values: Record<string, string | number | boolean>; fields: Field[] }
