const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
const path = require('node:path')

;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: 'zh-CN' })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  try {
    await page.goto('http://127.0.0.1:8011/#projects')
    await page.getByRole('heading', { name: '项目看板' }).waitFor()
    for (const title of ['已逾期', '进行中', '电池类', '干烧类', '配件类']) assert.equal(await page.locator('.project-board-card').filter({ hasText: title }).count(), 1)
    await page.locator('.project-board-card').filter({ hasText: '电池类' }).click()
    assert.equal(await page.locator('.project-selector').count(), Number(await page.locator('.project-board-card').filter({ hasText: '电池类' }).locator('strong').innerText()))
    await page.locator('.project-board-card').filter({ hasText: '已逾期' }).click()
    assert.equal(await page.locator('.project-board-card').filter({ hasText: '已逾期' }).getAttribute('aria-pressed'), 'true')
    await page.getByRole('link', { name: '分类与字段' }).click()
    await page.getByRole('heading', { name: '分类与字段管理' }).waitFor()
    console.log('STEP=settings-loaded')
    if (!(await page.locator('.settings-row').filter({ hasText: '温控类' }).count())) {
      await page.getByRole('button', { name: '新增分类' }).click()
      await page.getByLabel('分类名称').fill('温控类')
      await page.getByRole('button', { name: '保存分类' }).click()
      await page.getByText('分类已保存').waitFor()
    }
    if (!(await page.locator('.settings-row').filter({ hasText: 'priority_level' }).count())) {
      await page.getByRole('button', { name: '新增字段' }).click()
      await page.getByLabel('字段标识').fill('priority_level')
      await page.getByLabel('字段名称').fill('项目优先级')
      await page.getByLabel('字段类型').selectOption('select')
      await page.getByLabel('候选选项').fill('高，中，低')
      await page.getByRole('button', { name: '保存字段' }).click()
      await page.getByText('字段已保存').waitFor()
    }
    console.log('STEP=taxonomy-ready')
    await page.getByRole('link', { name: '研发项目' }).click()
    console.log('STEP=projects-open')
    await page.locator('.project-board-card').filter({ hasText: '全部项目' }).click()
    await page.getByLabel('所属分类').selectOption({ label: '温控类' })
    await page.getByLabel('项目优先级').selectOption('高')
    await page.getByRole('button', { name: '保存分类与字段' }).click()
    console.log('STEP=project-meta-clicked')
    await page.getByText('分类与字段已保存').waitFor()
    await page.locator('.project-board-card').filter({ hasText: '温控类' }).click()
    assert.equal(await page.locator('.project-selector').count(), 1)
    await page.screenshot({ path: path.join(process.cwd(), 'test-results', 'board-categories', 'project-board.png'), fullPage: true })
    console.log('STEP=project-verified')
    await page.getByRole('link', { name: '报告与任务' }).click()
    await page.getByRole('tab', { name: /产品类型报告/ }).waitFor()
    await page.locator('.report-title').first().click()
    console.log('STEP=report-open')
    await page.locator('.report-dialog').getByLabel('所属分类').selectOption({ label: '市场类型报告' })
    await page.locator('.report-dialog').getByRole('button', { name: '保存分类与字段' }).click()
    await page.locator('.report-dialog').getByText('分类与字段已保存').waitFor()
    await page.getByRole('button', { name: '关闭报告' }).click()
    await page.getByRole('tab', { name: /市场类型报告/ }).click()
    assert.ok(await page.locator('.report-row').count() >= 1)
    await page.screenshot({ path: path.join(process.cwd(), 'test-results', 'board-categories', 'report-types.png'), fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    const mobileWidth = await page.evaluate(() => document.documentElement.scrollWidth)
    assert.ok(mobileWidth <= 391, `mobile overflow ${mobileWidth}`)
    assert.deepEqual(errors, [])
    console.log(JSON.stringify({ status: 'PASS', projectFilters: 5, customCategory: '温控类', customField: '项目优先级', categoryFilteredProjects: 1, reportType: '市场类型报告', mobileWidth, browserErrors: errors.length }, null, 2))
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
