const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const errors = []
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: 'zh-CN' })
  page.on('pageerror', error => errors.push(error.message))
  try {
    await page.goto('http://127.0.0.1:8011/#knowledge')
    await page.getByRole('heading', { name: '研发流程知识库' }).waitFor()
    assert.match(await page.locator('.kb-intro-count strong').innerText(), /\d+/)
    await page.getByRole('tab', { name: /EVT/ }).click()
    await page.getByLabel('关联项目').selectOption('demo-project-1')
    await page.locator('.kb-index-item').filter({ hasText: 'T1测试报告' }).click()
    await page.getByRole('heading', { name: 'T1测试报告' }).waitFor()
    const create = page.getByRole('button', { name: '按模板创建' })
    const edit = page.getByRole('button', { name: '编辑文档' })
    if (await create.count()) await create.click(); else await edit.click()
    const body = page.getByLabel('Markdown 文档内容')
    const original = await body.inputValue()
    await body.fill(original + '\n本地预览验证：此条为演示内容，不代表真实测试结论。\n')
    await page.getByRole('button', { name: '保存文档' }).click()
    await page.getByText('文档已保存到本地工作空间').waitFor()
    await page.reload()
    await page.getByRole('tab', { name: /EVT/ }).click()
    await page.getByLabel('关联项目').selectOption('demo-project-1')
    await page.locator('.kb-index-item').filter({ hasText: 'T1测试报告' }).click()
    await page.getByText(/本地预览验证：此条为演示内容/).waitFor()
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: '下载 MD' }).click()
    const download = await downloadPromise
    const target = path.join(process.cwd(), 'test-results', 'knowledge-base', 'downloaded.md')
    await download.saveAs(target)
    assert.match(fs.readFileSync(target, 'utf8'), /本地预览验证/)
    await page.screenshot({ path: path.join(process.cwd(), 'test-results', 'knowledge-base', 'desktop.png'), fullPage: true })
    await page.goto('http://127.0.0.1:8011/#projects')
    await page.getByRole('heading', { name: '项目列表' }).waitFor()
    await page.getByRole('button', { name: '阶段文档' }).click()
    await page.getByRole('heading', { name: '研发流程知识库' }).waitFor()
    assert.equal(await page.getByRole('tab', { name: /EVT/ }).getAttribute('aria-selected'), 'true')
    assert.equal(await page.getByLabel('关联项目').inputValue(), 'demo-project-1')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: path.join(process.cwd(), 'test-results', 'knowledge-base', 'mobile.png'), fullPage: true })
    const width = await page.evaluate(() => document.documentElement.scrollWidth)
    assert.ok(width <= 391, `mobile overflow ${width}px`)
    assert.deepEqual(errors, [])
    console.log(JSON.stringify({ status: 'PASS', url: page.url(), templateCount: await page.locator('.kb-intro-count strong').innerText(), document: 'T1测试报告', saved: true, reloaded: true, downloaded: path.basename(target), mobileWidth: width, browserErrors: errors.length }, null, 2))
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
